name: lchika # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A caracalla gpio test snap # 79 char long summary
description: |
  This is caracalla's gpio test snap. Just for gpio interfaces debugging
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  gpiotest:
    # See 'snapcraft plugins'
    plugin: dump

apps:
    gpiotest:
        command: gpiotest
        plugs:
        - gpio
